# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('slug', models.SlugField(max_length=24, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('broken', models.BooleanField(default=False)),
            ],
        ),
    ]
